### ISSUE TITLE
Discussion deployment

### ISSUE THREAD

**Issue by slamer59** [BIX-Digital/mlflow-openshift#4] opened 2021-02-27 10:10 UTC
Hello,
I have a few questions. I am not an expert of Openshift so correct me if I don't use appropriate term. 

Which openshift version is used? 3 and 4 compatible?
Is it possible to launch deployment from an Openshift Node ? I think I can do it for example with python API.

My use case is to listen for a change in the registry of mlflow and when a model appears in stagging/Production I want to launch a deployment on Openshift on another node. 

I don't use AWS for storage. Is it mandatory ? I have another storage system. 

Do you think we can deploy few models on the same node ? Or I need to make a specific application for that ?

Thanks for your contribution!

**Comment by slamer59** [comment] 2021-02-27 16:05
To answer question: on AWS dependency.

https://github.com/BIX-Digital/mlflow-openshift/blob/1909191503ec2071d6f1f4e79cd859e7d7ad15e2/mlflow_openshift/utils.py#L26

**Comment by gerardcl** [comment] 2021-03-05 12:37
Hi @slamer59!

First, sorry for the delay on answering, we are on a besteffort mode :)

Regarding OpenShift clusters versions compatibility, so far we have fully tested it on OpenShift 3 and in the next days we are going to validate its behaving as expected also in OpenShift 4. We will update the docs once we have it confirmed.

Regarding launching deployments from an OpenShift node, I do not see any caveat on that meanwhile you have the right secrets/configs in place.

Regarding the AWS storage, so far as you can see in the template here:
https://github.com/BIX-Digital/mlflow-openshift/blob/1909191503ec2071d6f1f4e79cd859e7d7ad15e2/mlflow_openshift/templates/deploy_with_auth.yml#L119
the setup expects to connect to an S3-like storage.

This means that by default this is not supported but we can easily add other storage types. Let us know if you want to contribute on this.

**Comment by slamer59** [comment] 2021-03-05 16:00
Thanks for your feedback.
Really interersting. 

I develop an mlflow-jfrog-artifactory (I wish to release...)
I think there is only a small trick to make it more general with any artifact store. I will think about it. 

I read that yaml can read another yaml. Maybe ?
https://stackoverflow.com/a/52676097/4989371 

I keep you posted

**Comment by gerardcl** [comment] 2022-12-02 09:44
closing this issue since there has not been activity for more than a year

**Closed as completed by gerardcl** 2022-12-02 09:44 UTC
